---
custom:
  width: 240
  height: 90
  unit: 536871737
custom2:
  width: 300
  height: 90
  unit: 537234517
leaderboard:
  width: 728
  height: 90
  unit: 536871739
towerview_leaderboard:
  width: 728
  height: 90
  unit: 537147352
medium_rectangle:
  width: 300
  height: 250
  unit: 536871740
medium_rectangle_1:
  width: 300
  height: 250
  unit: 536871741
medium_rectangle_2:
  width: 300
  height: 250
  unit: 536871744
