---
- name: Big Blog
  id: 1001
  description: A closer look at Duke by students and for students.
- name: Blue Zone
  id: 1002
  logo: blogs/bluezone-logo.jpg
  banner: blogs/bluezone-banner.jpg
  description: Your one-stop shop for all the latest in Duke basketball, football, and more.
  twitter_widgets:
    - 295248698340933632
    - 372912145349894144
- name: Playground
  description: Arts and culture at Duke, Durham and beyond.
  section_id: 1003
