---
bigblog:
  name: Big Blog
  logo: blogs/bigblog-logo.jpg
  banner: blogs/bigblog-banner.jpg
  description: "Features and multimedia that that a closer look at Duke from students' perspective."
bluezone:
  name: Blue Zone
  logo: blogs/bluezone-logo.jpg
  banner: blogs/bluezone-banner.jpg
  description: Your one-stop shop for all the latest in Duke basketball, football, and more.
playground:
  name: Playground
  logo: blogs/playground-logo.jpg
  banner: blogs/playground-banner.jpg
  description: Arts and culture at Duke, Durham and beyond.
