---
bluezone:
  name: Blue Zone
  image: blogs/sportsblog-banner.jpg
  description: Eligendi enim ducimus hic similique autem ea aliquam assumenda id et ut dolor accusantium.
playground:
  name: Playground
  image: blogs/newsblog-banner.jpg
  description: Ullam qui dignissimos atque optio aut voluptatum consectetur enim consequatur officia fugiat.
backpages:
  name: Backpages
  image: blogs/newsblog-banner.jpg
  description: Aliquid tempore corporis est aliquam nesciunt et aut quasi illum iusto ab officia voluptas cupiditate in.
