development:
  adapter: postgresql
  database: chronline_development
  username: postgres
  password: postgres
  host: localhost

test: &test
  adapter: postgresql
  database: chronline_test
  username: postgres
  password: postgres
  host: localhost

production:
  adapter: postgresql
  database: chronline_production
  username: postgres
  password: postgres
  host: localhost
