development:
  adapter: postgresql
  database: development
  username: postgres
  password: postgres
  host: localhost

test: &test
  adapter: postgresql
  database: test
  username: postgres
  password: postgres
  host: localhost

production:
  adapter: postgresql
  database: production
  username: postgres
  password: postgres
  host: localhost
