---
rectangle:
  width: 636
  height: 393
  sizes:
    - 606
    - 468
    - 378
    - 314
    - 183
    - 152
square:
  width: 200
  height: 200
  sizes:
    - 150
    - 80
    - 70
banner:
  width: 636
  height: 212
  sizes:
    - 606
    - 300
    - 216
vertical:
  width: 243
  height: 393
  sizes:
    - 183
